### ISSUE TITLE
Sequelize.sync() error

### ISSUE THREAD

**Issue by Ywoosang** [frasnym/Docker-NodeJS-MySQL#1]
Thank you for the post.
There's a problem with the implementation.
The first compose-up results in an error in which mysql connections are rejected. 
but enter the compose-up command again, it connects normally.  
I can't find the cause, so I'm attaching the error.
Thank you.
```bash
ywoosang@ws ~/Docker-NodeJS-MySQL (main) $ docker-compose up
Creating network "docker-nodejs-mysql_default" with the default driver
Creating docker-nodejs-mysql_db_1 ... done
Creating docker-nodejs-mysql_app_1 ... done
Attaching to docker-nodejs-mysql_db_1, docker-nodejs-mysql_app_1
db_1   | 2021-04-23 15:38:52+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.24-1debian10 started.
db_1   | 2021-04-23 15:38:52+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
db_1   | 2021-04-23 15:38:52+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.24-1debian10 started.
db_1   | 2021-04-23 15:38:52+00:00 [Note] [Entrypoint]: Initializing database files
db_1   | 2021-04-23T15:38:52.910518Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.24) initializing of server in progress as process 41
db_1   | 2021-04-23T15:38:52.913430Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
db_1   | 2021-04-23T15:38:53.123343Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
app_1  | 
app_1  | > node-mysql-app@1.0.0 start /app
app_1  | > node index.js
app_1  | 
app_1  | Worker: process 20 is up on port 3000
app_1  | ConnectionRefusedError [SequelizeConnectionRefusedError]: connect ECONNREFUSED 172.24.0.2:3306
app_1  |     at ConnectionManager.connect (/app/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:116:17)
app_1  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
app_1  |     at async ConnectionManager._connect (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:318:24)
app_1  |     at async /app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:32
app_1  |     at async ConnectionManager.getConnection (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:280:7)
app_1  |     at async /app/node_modules/sequelize/lib/sequelize.js:613:26
app_1  |     at async MySQLQueryInterface.createTable (/app/node_modules/sequelize/lib/dialects/abstract/query-interface.js:225:12)
app_1  |     at async Function.sync (/app/node_modules/sequelize/lib/model.js:1300:5)
app_1  |     at async Sequelize.sync (/app/node_modules/sequelize/lib/sequelize.js:793:35) {
app_1  |   parent: Error: connect ECONNREFUSED 172.24.0.2:3306
app_1  |       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
app_1  |     errno: -111,
app_1  |     code: 'ECONNREFUSED',
app_1  |     syscall: 'connect',
app_1  |     address: '172.24.0.2',
app_1  |     port: 3306,
app_1  |     fatal: true
app_1  |   },
app_1  |   original: Error: connect ECONNREFUSED 172.24.0.2:3306
app_1  |       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
app_1  |     errno: -111,
app_1  |     code: 'ECONNREFUSED',
app_1  |     syscall: 'connect',
app_1  |     address: '172.24.0.2',MYSQL_HOST
app_1  |     port: 3306,
app_1  |     fatal: true
app_1  |   }
app_1  | }
```

**Comment by frasnym** [comment]
Please use english, so I can understand 😔
But, from the error, maybe you have to specify the right DB host for your app.
Example: set your app env `MYSQL_HOST=mysqldb`

**Comment by frasnym** [comment]
> 안녕하세요
> 포스트 잘 읽었습니다.
> 실행 관련해서 문제점이 있는데
> 첫번째 compose-up 을 하면 다음과 같이 mysql 연결이 거부되는 오류가 발생합니다.
> 다시한번 compose-up 커맨드를 입력하면 정상적으로 연결이 됩니다.
> 원인이 무엇인지 찾을 수 없어 해당 오류를 첨부합니다.
> 감사합니다.
> 
> ```shell
> ywoosang@ws ~/Docker-NodeJS-MySQL (main) $ docker-compose up
> Creating network "docker-nodejs-mysql_default" with the default driver
> Creating docker-nodejs-mysql_db_1 ... done
> Creating docker-nodejs-mysql_app_1 ... done
> Attaching to docker-nodejs-mysql_db_1, docker-nodejs-mysql_app_1
> db_1   | 2021-04-23 15:38:52+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.24-1debian10 started.
> db_1   | 2021-04-23 15:38:52+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
> db_1   | 2021-04-23 15:38:52+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.24-1debian10 started.
> db_1   | 2021-04-23 15:38:52+00:00 [Note] [Entrypoint]: Initializing database files
> db_1   | 2021-04-23T15:38:52.910518Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.24) initializing of server in progress as process 41
> db_1   | 2021-04-23T15:38:52.913430Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
> db_1   | 2021-04-23T15:38:53.123343Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
> app_1  | 
> app_1  | > node-mysql-app@1.0.0 start /app
> app_1  | > node index.js
> app_1  | 
> app_1  | Worker: process 20 is up on port 3000
> app_1  | ConnectionRefusedError [SequelizeConnectionRefusedError]: connect ECONNREFUSED 172.24.0.2:3306
> app_1  |     at ConnectionManager.connect (/app/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:116:17)
> app_1  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
> app_1  |     at async ConnectionManager._connect (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:318:24)
> app_1  |     at async /app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:32
> app_1  |     at async ConnectionManager.getConnection (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:280:7)
> app_1  |     at async /app/node_modules/sequelize/lib/sequelize.js:613:26
> app_1  |     at async MySQLQueryInterface.createTable (/app/node_modules/sequelize/lib/dialects/abstract/query-interface.js:225:12)
> app_1  |     at async Function.sync (/app/node_modules/sequelize/lib/model.js:1300:5)
> app_1  |     at async Sequelize.sync (/app/node_modules/sequelize/lib/sequelize.js:793:35) {
> app_1  |   parent: Error: connect ECONNREFUSED 172.24.0.2:3306
> app_1  |       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
> app_1  |     errno: -111,
> app_1  |     code: 'ECONNREFUSED',
> app_1  |     syscall: 'connect',
> app_1  |     address: '172.24.0.2',
> app_1  |     port: 3306,
> app_1  |     fatal: true
> app_1  |   },
> app_1  |   original: Error: connect ECONNREFUSED 172.24.0.2:3306
> app_1  |       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
> app_1  |     errno: -111,
> app_1  |     code: 'ECONNREFUSED',
> app_1  |     syscall: 'connect',
> app_1  |     address: '172.24.0.2',
> app_1  |     port: 3306,
> app_1  |     fatal: true
> app_1  |   }
> app_1  | }
> ```

Please use english, so I can understand 😔
But, from the error, maybe you have to specify the right DB host for your app.
Example: set your app env MYSQL_HOST=mysqldb

**Comment by Ywoosang** [comment]
Thank you for your answers.
I made it based on what you told me :) 
I changed the file as below and set the host as the container name inside the application, 
so it works without any problems.!!! 
```docker
version: '3.7'

services: 
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: servicedb
      MYSQL_HOST: mysql
    ports:
      - 3306:3306
  app:
    build:
      context: ./app
    image: ywoosang/wlearn
    container_name: wlearn-app
    environment:
      DB_USERNAME: root
      DB_HOSTNAME: mysql
      DB_DATABASE: servicedb
      DB_PASSWORD: password
    ports:
      - 3000:3000
    depends_on:
      - mysql
    stdin_open: true
    tty: true
```

```js 
const sequelize = new Sequelize(
	'servicedb',
	'root',
	'password',
	{  // from config.json
		dialect: 'mysql',
		port: 3306,
		logging: false,
		username:'root',
		host: 'mysql',
		database: 'servicedb',
		password:  'password'
	}
);
```
